// AboutDlg.h
// Copyright (c) 2018 by Jim Pattee <jimp03@email.com>.
// This code is licensed under the MIT License.
// License.md describes the conditions under which this software may be distributed.

#ifndef _ABOUTDLG_H_
#define _ABOUTDLG_H_

//-----------------------------------------------------------------------------
// headers
//-----------------------------------------------------------------------------

#include "AboutDlgBase.h"

//-----------------------------------------------------------------------------
// AboutDlg Class
// The inherited AboutDlgBase class is generated by wsFormBuilder
//-----------------------------------------------------------------------------

class AboutDlg: public AboutDlgBase
{
public:
	explicit AboutDlg(wxWindow* parent);
	void SetAboutDlgValues(wxString& astyleVersion, wxIconBundle* m_iconBundle);

private:
	void SetSystemInfo();
};

#endif	// _ABOUTDLG_H_
